### PR TITLE
I tried to add an update to the autoHeight to match the current slide 

### PR DESCRIPTION
**Pull request by salahaa1**
I tried to add an update to the autoHeight to match the current slide not only to the first slide or the heights one , but to be the height of the current slide , which will not leave any empty space on shorter ones.

just change the autoHeight: 'currentSlide'

regards

### CODE REVIEW

**Comment by malsup** [comment]
Demo: http://jquery.malsup.com/cycle2/demo/container-resize.php

**Comment by josefch** [comment]
Hi,
If I use this with data-cycle-hash for my elements, the setting of the height won't work at load for the first slide  (subsequent clicks ok then) - any chance to fix this?
Best
Josef

**Comment by nonemos** [comment]
same problem. Didi you fix it?

**Comment by struiling** [comment]
Also seeing this behavior (or lack thereof), on the first slide only.

**Pull request closed without merging**
